hacktoberfest17/programming

hello_world/hello_world.rb
=> hellow_world in ruby

hello_world/hello_world_py2.py, hello_world/hello_world_py3.py
Added python 2 and 3 Hello World script.
=> Hello World in Python 2 and 3

hello_world/hello_world.c
Creating a hello world program in C
=> Creating a hello world program in C

linked_list/LinkedList.py
Program Includes
* Linked List Insertion
* Linked List Deletion
* Printing Nodes
=> Created Linked List Program in Python 

Loops/Factorial_Whileloop.cpp, Loops/Factorial_forLoop.cpp, Loops/Sum_do_while.cpp
Contains basic loops(for loop, while loop and do-while loop).
=> Looping Examples

hello_world/hello_world.c
=> Add Hello World in C

hello_world/hello_world.rs
It is a basic example for rust.
=> Added hello_world example for rust.

README.md
https://github.com/hacktoberfest17/programming/issues/6
Some proofreading/editing in `README.md`.
=> Format reference links and some editing

hello_world/hello_world.java
https://github.com/hacktoberfest17/programming/issues/54
=> Hello World Java

count_the_age_person/count_the_age_person.cpp
#13 added a program to count the age person in c++
=> add program to count the age person in c++

hello_world/hello_world.cpp
Intendation and comments improve the the value of a program
=> Added intendation and comment

CONTRIBUTORS.md, Sorting/Python/Radix Sort/radixsort.py
=> Fix for issue #70

fibonacci/Fibonacci.java
=> add fibonacci series in java

is_palindrome/is_palindrome.py
=> is_palindrome in python

recursion/factorial.go
Closes hacktoberfest17/programming#154
=> Factorial in Go

is_palindrome/is_palindrome.js
=> Is Palindrome in JavaScript

fibonacci/fibonacci.rkt
=> Add fibonacci in Racket

factorial/factorial.rkt
=> Add factorial in Racket

linear_search/linear_search.js
=> Add linear search implementation in JavaScript

hello_world/hello_world.sh
=> Adds Hello World Program in BASH

linear_search/linear_search.java
=> Added Linear search in Java

hello_world/hello_world.sh
Adding hello world code in bash
=> Hello world in bash

fibonacci/Fibonacci.cs
Print Fibonacci series in C#.
Participating in Hacktoberfest!
=> Print Fibonacci series in C#. Fixes issue #119.

fibonacci/fibonacci.py, linear_search/README.md, linear_search/linear_search.py
Add linear_search.py and README.md
=> Linear Search program in Python

binary_search/Balancebinarytree.c
This is the code in C for balancing a binary tree with respect to issue #41
=> Add balance binary tree code

is_palindrome/is_palindrome.cpp
=> Added Palindrome checker in cpp

selection_sort/selection_sort.java
=> Added Selection Sort in Java

factorial/Factorial.java
Please Review my code this is a factorial program used Java
=> Java_Factorial_Program

recursion/tower_of_hanoi.java
=> Added Tower of Hanoi in Java

hello_world_php/index.php
#61  please check this  #46 ... thanks
=> #46 adding hello world in index.php

hello_world_php/index.php
fixes #190 
As hello_world.php already existed in the hello_world folder, removed the hello_world_php folder.
=> Removed hello_world_php folder

hello_world.m
Closes issue https://github.com/hacktoberfest17/programming/issues/187
=> hello_world/hello_world.m: Add hello_world.m to hello_world directory.

insertion_sort/README.md, selection_sort/README.md
Added README.md to insertion_sort
=> Issue - insertion_sort algorithm #204

linear_search/linear_search.go
=> Added linear search in Go

binary_search/binary_search.go
=> Added Binary Search in Golang

recursion/towerofhanoi.go
=> added tower of hanoi in golang

function_composition/composition.js
This PR adds a simple helper function to help with function composition. (Ref: #17)
=> Add function composition

BFS/README.txt
=> Merged bfs directories

java_objects/Student.java
=> Program to explain the use of objects in java

factorial/factorial.swift
Closes https://github.com/hacktoberfest17/programming/issues/193
=> factorial implementation in Swift

hello_world/hello_world.ml
=> Add Hello world in OCaml(closes #227)

hello_world/hello_world.lisp
=> Add Hello world in lisp (closes #231)

MultiThreaded_DotProduct/multi_thread_dot_product.c
=> Added C program file.

factorial/Factorial.py
=> update factorial for python3

hello_world/hello_world.py
=> Added hello world script compatible with both Python 2 and Python 3 - Fix #237

factorial/factorial.py
This pull request fixes #(240)
=> fix issue #240

factorial/factorial.go
=> Added Golang implementation of factorial

is_prime/is_prime.py
=> Creating a pull request , to check whether a number is a  prime or not

is_palindrome/is_palindrome.cs
=> Added Palindrome Checker in C#

fp_in_js/index.js
added some examples of functional programming in javascript resolve #17
=> feat(fp_in_js): added basics of FP in JS

factorial/factorial.cs
=> added c# factorial

recursion/TowerOfHanoi.py
=> Added Tower of Hanoi in Python

linked_list/linked_list.py
for [issue #35](https://github.com/hacktoberfest17/programming/issues/35)
=> added a linked list implemented in python3

fibonacci/Fibonacci-with-Memoization.py
=> Added 'Fibonacci-with-Memoization.py' to fibonacci

factorial/Factorail.vb
=> add factorial function using vb.net

web_server/web_server.js
=> added a web server in javascript

CompaniesRank/empresa.py, CompaniesRank/main.py, CompaniesRank/puntuacion.py
=> Added CompaniesRank program in python #277

hello_world/hello_world.c
=> int to void and getch() included

reverse_a_number/reverse_number.cs
Added example reverse number code for C#
=> Add Reverse a Number C# example

hello_world/helloworld.c
=> helloworld.c

recursion/Ackermann.cs
=> Added Ackermann Function in C#

is_prime/is_prime_cli.php
=> add php script to check if number is prime (fixes #284)

call_by_reference/reference.c
#271 This pull request fixes #(issue number)
=> call by reference in c 

fibonacci/fibonacci.py
Change fibonnaci python file to run with python v2.7 and v3.6
=> Update fibonacci python file to run with versions 2.7 and 3

call_by_reference/call_by_reference.c, multi threading/Create thread and run.java, multi threading/Thread extension.java
This pull request fixes #260 and #271
=> closes issues #260 and #271

binary_search/binary-search.cpp
=> Added binary search in c++

factorial/factorial.rs
=> Add factorial function in Rust

fibonacci/fibonacci.php
=> add fibonacci.php (fixes #304)

factorial/Factorial.py, factorial/factorial.py, fibonacci/fibonacci.py
Change for versions 2.7 and 3.
=> Update to run in version 2;7 and 3

CONTRIBUTING.md, README.md
=> Improve README.md and CONTRIBUTING.md

bfs/README.txt
=> remove extra bfs directory, resolves #225

hello_world/hello_world_kt2.kt
=> - Fixes Issue #308

recursion/BinarySearch.cpp
Added Binary Search in C++ #317
=> Added Binary Search in C++ #317

encryption_algorithms/stream_cipher.js
=> Add stream cipher in javascript

is_prime/is_prime.cpp
=> Added Prime Checker in Cpp

is_prime/is_prime.cpp
=> Added is_prime.cpp

is_palindrome/is_palindrome.rs
=> Add a 'is palindrome' function in rust

count_the_age_person/count_age_of_person.py
=> add python age counter with datetime, resolves #325

sorting/quick_sort/quick_sort.js
=> Add quicksort for js

sorting/quick_sort/quick_sort.js
=> Sorting, added quick sort algorithm implementation in javascript

polynomial_addition_linkedList/polyAdd.c
=> fixes - #329

fibonacci/fibonacci.js
=> Add fibonacci for JavaScript

fibonacci/fibonacci.js
Based in this version. (https://stackoverflow.com/questions/7944239/generating-fibonacci-sequence)
This pull request fixes #334
=> Create fibonacci in javacript

recursion/Ackermann.py
=> Added Ackermann Function in Python

password_generator/password_generator.py
Add password generator in python
#264
=> Add password generator function based on username and validate password function

password/password.py
=> Password functions

binary_search/BinarySearch.cs
=> Created Binary Search In C#

hello_world/hello-world.cpp
=> Added hello-world.cpp in hello_world

Companies_Rank/empresa.py, Companies_Rank/main.py, Companies_Rank/puntuacion.py, multi_threading/Create thread and run.java, multi_threading/Thread extension.java
=> Update for #313 rename CompaniesRank

client_server_interaction/client.py, client_server_interaction/server.py
=> V3nturetheworld client server interaction in python

.gitignore, is_prime/is_prime.ts, package.json
- Added is prime in typescript.
- Added typescript env config for running ts file. 
- This pull request fixes #301
=>  Added is prime in typescript

is_palindrome/is_palindrome.php
=> added a php script to check if the entered string is palindrome or not

README.md
This pull request fixes #(426)
=> Corrected the typo

gcd/gcd.py
=> Added GCD in Python

count_the_age_person/age_counter.sh
=> Add age counter in bash.

fibonacci/fibonacci.sh
=> Add fibonacci in Bash

tic-tac-toe/tic-tac-toe.c
=> Added Tic tac toe algorithm in c

Kmp/kmp.cpp, Segment_trees/segtrees.cpp
=> Segment trees in c++

HelloWorld.java, factorial/factorial.py
=> Samfrey99 hello world in java

factorial_dp/factorial.py
=> factorial with dp

Applet in  java/README.md, Applet in  java/car.java
=> Applet Programmming

hello_world/hello_world(HTML).html
=> Hello World (HTML)

nlp/NLP_program.py
This pull request fixes #(394)
=> Natural language processing in python #394

sorting/Heap_Sort.cpp
Input type:
first line: enter no. of elements(n)
second line: enter n elements
=> Heap_sort cpp implementation uploaded

natural_language_processing_python/named_entity_recognition.py, natural_language_processing_python/speech_tagging.py
This pull request fixes #(394)
=> added speech tagging in nlp python

Union_find/union_find_set.cpp
=> Implemented union find template

Binary_Trees/constructBST_Using_Inorder_Postorder.java
=> construct BST from inorder and postorder in java

tic-tac-toe/TicTacToe.java
resources : Udemy course practice project
=> added Tic-tac-toe in java

linked_list/detect_loop_in_link_list.java
=> detect loop in link list java

gcd/gcd.c
=> Adds GCD of two numbers inC

gcd/gcd.java
=> GCD of two numbers in JAVA

nqueens/nqueens.c
Implementing N-Queens problem solution in C 
Issue: #468
=> N-Queens problem in C

sorting/quick_sort/quicksort.py
=> Added quicksot in python 3

password_generator/pw_checker.py
=> Yet another password strength checker

sorting/bubble_sort/bubble_sort.swift
=> Add Bubble Sort in Swift

reverse_a_number/ReverseNumber.scala
https://github.com/hacktoberfest17/programming/issues/485
=> Scala program to reverse a number using Queue

odd_even/instructions.txt, odd_even/odd_even.cpp
This pull request fixes #491
It says if a number is odd or even
=> odd_even in c++

bit_operation/BitsQuestion.cpp
=> Next highest number with same no. of set bits

sorting/selection_sort/selection_sort/selectionSortDescending.js
=> Added descending selection sort in javascript

gcd/gcd.cs
=> Added GCD in C#

totient_function/totient_function.cpp
=> Added Totient Function in C++

sorting/merge_sort/merge_sort.java
=> Added Merge Sort in Java

factorial/factorial_using_dp/factorial.py
=> Fix Issue #465

is_prime/sieve-prime.swift
=> Initial upload

gcd/gcd.cpp
An interative gcd function written in cpp
=> Added iterative gcd function

factorial/factorial.go, loop/sum_forLoop.go, recursion/factorial.java
=> Added for loop in Go

machine_learning/Kmeans/kmeans.py
=> Kmeans simplistic version

binary_search/binary.c
=>  Addded binary search in C

sorting/insertion_sort/insertion.c
=> Added insertion sort in C

twin_primes/README.md, twin_primes/twinprimes.java
=> to calculate twin primes in a given range. 

totient_function/totient_function.py
=> Added Totient Function in Python

web_server/java/web_server.java
=> added web server in java

check_ean_13/js/ean13.js
=> Fixed Bug in checkean13, fixes #556

sorting/bubble_sort/bubble_sort.c
=> fixes #559

prime_factors/prime_factors.cs
=> Added Prime Factors in C#

prime_number/bash/prime.sh
- [ /] This pull request fixes #563 (Create a issue if not already present.)
- [ /] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [ /] Don't duplicate stuff.
=> Add prime_numbers (Bash)

NthFibonacci/NthFibonacci.java, NthFibonacci/README.md
This pull request fixes #478
The directory structure is of the form (NthFibonacci)
=> Added O(logn) algorithm to find fibonacci term

CONTRIBUTORS.md, fetch_contributors.py
=> added contributors fetching

prime_factors/prime_factors.py
=> Added Prime Factors in Python

is_prime/ruby/prime_number.rb
=> Add is_prime for Ruby

prime_factors/prime_factors.java
=> Added Prime Factors in Java

is_palindrome/haskell/is_palindrome.hs
=> add haskell is_palindrome

sorting/bucket_sort/bucket_sorting.kt
=> Added bucket sort in Kotlin

prime_factors/prime_factors.cpp
=> Added Prime Factors in C++

BinaryTree/BinaryTree.h, BinaryTree/main.cpp, dequeue/dequeue.h, dequeue/main.cpp
=> Added binary tree code

dequeue/dequeue.h, dequeue/main.cpp
=> added dequeue example

fibonacci/haskell/fibonacci.hs
=> Write Fibonacci sequence calculator in Haskell

oodle/oodle.lua
---
Lua is a great programming language for beginners to pick up. I started programming in Lua when I came across the game framework [LÖVE](https://love2d.org/), which is also fun to mess around with with starting out. You can check out their Getting Started guide [here](https://love2d.org/wiki/Getting_Started).
Have fun oodle-ifying your name!
=> Oodle in Lua - fixes #607

NthFibonacci/NthFibonacci.cpp
- [*] This pull request fixes #603
- [*] The directory structure is of the form (NthFibonacci) 
- [*] Don't duplicate stuff.
=> Added NthFibonacci.cpp

is_prime/js/is_prime.js
=> is_prime in js

recursion/go/factorial.go
=> Adding custom input

fibonacci/go/fibonacci.go
=> Updating code to work as described by README

palindrome/palindrome.c
- [*] This pull request fixes #593  
- [*] The directory structure is of the form (palindrome/palindrome.c) (If directory doesn't exist, create a new.)
- [*] Don't duplicate stuff.
=> Adds Palindrome program in C

babylonian_square_root/babylonian_square_root.cpp
=> Added Babylonian Square Root in C++

brackets/README.md, brackets/java/brackets.java
=> Solve simple balanced brackets task.

password_generator/go/pwgen.go
=> added password generator in go

is_adam_number/Readme.txt, is_adam_number/cpp/adam.cpp
For issue #624 , development has started
=> making new folder

brackets/cpp/brackets.cpp
Fixes issue https://github.com/hacktoberfest17/programming/issues/628
Pull Request checklist -
=> created brackets.cpp

babylonian_square_root/babylonian_square_root.py
=> Added Babylonian Square Root in Python

babylonian_square_root/babylonian_square_root.cs
=> Added Babylonian Square Root in C#

babylonian_square_root/babylonian_square_root.java
=> Added Babylonian Square Root in Java

compression_algo/austinpowers.txt, compression_algo/huffman.c, compression_algo/huffman_compressed file.c
=> added huffman algorithm code in c

NthFibonacci/NthFibonacci.js
=> Add Nth Fibonacci for Javascript

gcd/javascript/gcd.js
=> Add GCD for Javascript

babylonian_square_root/babylonian_square_root.js
=> Add Babylonian Square Root for Javascript

concurrency_robot/node.js/robot.js
=> Add Concurrency Robot for Node.js

tic_tac_toe/ruby/TicTacToe.rb
=> add ttt game methods on ruby in TicTacToe directory

shortest_fastest_foobar/foobar.js
=> Added folder and JS file for the fastest foobar

fibonacci/js/recursiveFibonacci.js
=> addign a new variant of fibonacci algrithm in js

loop/python/Factorial_forLoop.py
=> Happy Hacktoberfest

graphs/java/BFSPuzzle.java
This method solves the worst case scenarios in about 4 seconds.
- [ x ] This pull request fixes #657  (Create a issue if not already present.)
- [ x ] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [ x ] Don't duplicate stuff.
=> Added BFS implementation to solve the 8-Puzzle. Fix issue #657

babylonian_square_root/babylonian_square_root.sh
- [ /] This pull request fixes #655  (Create a issue if not already present.)
- [/ ] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [/ ] Don't duplicate stuff.
=> Add babylonian square root in bash

NthFibonacci/nthfibonacci.sh
- [ /] This pull request fixes #653 (Create a issue if not already present.)
- [/ ] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [ /] Don't duplicate stuff.
=> Add nthfibonacci in Bash

hello_world/Perl/helloworld.pl, hello_world/perl/helloworld.pl
=> add hello world in perl

combination/combination.cpp
=> Added Combination in C++

permutation/permutation.cpp
=> Added Permutation in C++

machine_learning/linear_regression/linear_regression.py, machine_learning/single_neuron/single_neuron.py
=> linear regression and single neuron with relu activation

index.html
HTML page that needs to be moved to gh-pages branch
#463
=> added index.html to master branch

sieve_of_eratosthenes/sieve.cpp, sieve_of_eratosthenes/smallest_prime_factor.cpp
=> Add sieve for finding primes

permutation/permutation.cs
=> Added Permutation in C#

permutation/permutation.java
=> Added Permutation in Java

permutation/permutation.py
=> Added Permutation in Python

combination/combination.cs
=> Added Combination in C#

combination/combination.java
=> Added Combination in Java

combination/combination.py
=> Added Combination in Python

httpracer/README.md, httpracer/httpracer.go, httpracer/httpracer_test.go
=> Fixes #691

CONTRIBUTORS.md, hello_world/clojure/helloworld.clj
Pull Request for Hello_World in Clojure #690
=> hello_world_clojure

NeuralNetwork/nn.py
=> Added neural network example

NeuralNetwork/nn.py
=> Added file downloader program

is_palindrome/ruby/is_palindrome.rb
=> Add is palindrome function in ruby

loop/php/Factorial_forLoop.php
=> tuvshuud_Factorial_for_Loop

multiples_of_3_and_5/go/multiples.go
=> added multiples_of_3_and_5 in go

pyTM/README.md, pyTM/pyTM.py, pyTM/todo.txt, simple_task_manager/README.md, simple_task_manager/pyTM.py, simple_task_manager/todo.txt
=> pyTM - CL task manager

nqueens/c/nqueenswithobstacles.cpp
=> Create nqueens with obstacles

binary_search/js/binary_search_tree_in_js.js
Implement Binary Search tree in Javascript using ES6 classes
=> Add binary search tree in  JavaScript

Hashtable/Hashtable_in_Js.js
Implement Simple hashtable implementation in Javascript
fixes #715
=> Add Javascript Hashtable file

hello_world/pascal/helloworld.pas
=> add hello world in pascal

linked_list/javascript/doubly_linkedlist_js.js
Implementation of basic Doubly Linked List in Javascript
fixes #720
=> Doubly linkedlist in js

sorting/Cocktail_Sort
=> coctail sort using cpp

sorting/sort_strings/sortcom.cpp
Input:
//sorts these string values
string names1[] = {"George","Penny","Estelle","Don","Mike","Bob"};
//converts these inches to centimetres
double inches[] = {3.5,6.4,6,7,8};
Output:
8.89 16.256 15.24 17.78 20.32 5.34025e-317 22.5806
Don is element 3 on the list
Bob
Don
Estelle
George
Mike
Penny
=> sortcom.cpp

fibonacci/java/fibonacci_dp.java, fibonacci/java/fibonacci_dp_space_optimized.java, fibonacci/java/fibonacci_matrix.java, fibonacci/java/fibonacci_matrix_time_optimized.java, fibonacci/java/fibonacci_recursion.java
=> Uploaded fibonacci variant program in Java

shell_scripting/arithmetic-float.sh, shell_scripting/arithmetic-operation.sh, shell_scripting/break-statement.sh, shell_scripting/case-statement.sh, shell_scripting/change-permission.sh, shell_scripting/continue.sh, shell_scripting/counting.sh, shell_scripting/elif.sh, shell_scripting/escape-sequence.sh, shell_scripting/file-test.sh, shell_scripting/for-loop.sh, shell_scripting/hello-world.sh, shell_scripting/if-then-else.sh, shell_scripting/if-then.sh, shell_scripting/ifs.sh, shell_scripting/input.sh
=> added shell scripting

factorial/shell/factorial.sh
=> shell factorial

IO_operations_C/classthatwrites.cpp
It is a C++ program which gives a demo for using IO classes in C++.
=> classthatwrites.cpp

icpc_problems/2015/Readme.md, icpc_problems/2015/problemA.cc
=> Added icpc_problems

is_pangram/is_pangram.cpp
=> Added Pangram Checker in C++

is_anagram/is_anagram.cpp
=> Added Anagram Checker in C++

palindrome/palindrome.java
=> palindrome in java

palindrome/palindrome.py
Can find if a string is a palindrome or if a series of characters can be arranged into a palindrome
=> Added Palindrome for Python

NthFibonacci/NthFibonacci.go
Pull Request checklist -  fixes #809
- [x ] This pull request fixes #809 (Create a issue if not already present.)
- [ x] The directory structure is of the form NthFibonacci/NthFibonacci.go (If directory doesn't exist, create a new.)
- [ x] Don't duplicate stuff.
=> Fibonacci in Go

sorting/quick_sort/QuickSort.java
=> Add QuickSort in java

prime_factors/prime_factors.rkt
Added prime_factors in racket lang
It uses 3 functions
- (prime?)
- (factorize)
- (factorize-function)
Call it using `(factorize <number you want to factorize>)`
Example: `(factorize 5460)`
`'((2 2) (3 1) (5 1) (7 1) (13 1))`
=> Added prime_factors in Racket

sorting/bubble_sort/bubble_sort.rb
=> added bubble sort in ruby

gcd/ruby/gcd.rb
=> added gcd function in ruby

min-hashing/file.txt, min-hashing/main.py
=> Adds min-hasing implemenation

hello_world/batch/hello_world.bat
=> Issue - Creating Hello World in batch fixes issue #802

hello_world/assembly/mips/hello_world.asm
Created the hello_world.asm code, should use any mips simulator to run it.
- [ok] This pull request fixes #issue_reference (Create a issue if not already present.)
- [ok] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [ok] Don't duplicate stuff.
=> created hello world in mips assembly for issue #798

loop/javascript/for-loop.js, loop/javascript/while-loop.js
Added JavaScript For and While loops in Loop directory
=> Mekowalski branch

is_palindrome/java/is_palindrome_recursive.java
This PR is add Palindrome checker with recursive way written in Java.
=> Add palindrome checker with recursive way in Java

MakeTimer/MakeTimer.js, MakeTimer/README.md, MakeTimer/example01.js
=> Hacktoberfest create MakeTImer

binary_search/java/binary_search.java, hello_world/js/hello_worldJS.js
java script application that prints out "Hello World" in console.
when you run it on your browser, if you cant  find where it prints hello world, simply press F12 and move to 'console' tab
=> created hello_worldJs.js

addition/add.cpp, bit_operation/cpp/swap_even_odd/swap.cpp, hello_world/Objective-C/main.m
=> Issue #781 fixed - Added swap.cpp

addition/add.cpp, hello_world/Objective-C/main.m
=> Added main.m to print "Hello World" in Objective-C

recursion/cpp/tower_of_hanoi.cpp
Adds tower of Hanoi recursion implementation in cpp - [label:hacktoberfest]
Pull Request checklist -
=> fixes #766 - Added Tower of Hanoi in cpp

addition/add.cpp, bit_operation/cpp/reversebits/reverse.cpp, hello_world/Objective-C/main.m
=> Issue #773 solved (Added reverse.cpp)

jquery-news-ticker/README.md, jquery-news-ticker/css/style.css, jquery-news-ticker/index.html, jquery-news-ticker/script/news-ticker.js
=> jquery-news-ticker

addition/add.cpp
=> Added program to add two numbers

is_anagram/is_anagram.py
=> Added Anagram Checker in Python

shell_scripting/logical-operators.sh, shell_scripting/nested-loop.sh, shell_scripting/pinfo.sh, shell_scripting/positional-parameters.sh, shell_scripting/reverse-quote.sh, shell_scripting/sleep.sh, shell_scripting/string.sh, shell_scripting/tput.sh, shell_scripting/until-loop.sh, shell_scripting/using-commands.sh, shell_scripting/while-loop.sh
=> added more shell scripting codes

is_anagram/is_anagram.java
=> Added Anagram Checker in Java

is_anagram/is_anagram.cs
=> Added Anagram Checker in C#

hello_world/cpp/helloworld.cpp, hello_world/js/helloworld.js, recursion/cpp/factorial.cpp
=> factorial of a small number using recursive function

is_pangram/is_pangram.cs
=> Added Pangram Checker in C#

is_pangram/is_pangram.java
=> Added Pangram Checker in Java

NthFibonacci/NthFibonacci.cs
=> NthFibonacci C# Solution

is_pangram/is_pangram.py
=> Added Pangram Checker in Python

encryption_algorithms/js/anubis.js
This file can be directly downloaded and imported to the working directory for encryption and decryption. #464
=> Added anubis block cipher algorithm. Issue #464

linked_list/linkedlist.c
=> linkedlist in c

basic_maths/add.cpp
=> Added add.cpp to basic_maths

sieve_of_eratosthenes/prime_factorization_in_logn_for_multiple_queries.cpp
This pull request fixes #845 
Time complexity - <**O(nloglogn), O(logn)**>
=> Added Prime Factorization of a number in logn for mulitple queries

android_tutorials/Tutorials.md
- [+] This pull request fixes #issue_reference (Create a issue if not already present.)
- [Android_Tutorials folder created]
- [+] Don't duplicate stuff.
=> Added Android Tutorials

string_palindromic_substring_count/StringPalindromicSubstringCount.java, string_palindromic_substring_count/java/StringPalindromicSubstringCount.java
=> adding string-palindromic-substring-count-#841 java code

linear_search/ruby/linear_search.rb
=> Added ruby script for linear search #834

Go_programming/constant.go, Go_programming/for.go, Go_programming/functions.go, Go_programming/hello.go, Go_programming/if-statement.go, Go_programming/switch.go, Go_programming/variables.go, shell_scripting/logical-operators.sh, shell_scripting/nested-loop.sh, shell_scripting/pinfo.sh, shell_scripting/positional-parameters.sh, shell_scripting/reverse-quote.sh, shell_scripting/sleep.sh, shell_scripting/string.sh, shell_scripting/tput.sh, shell_scripting/until-loop.sh, shell_scripting/using-commands.sh, shell_scripting/while-loop.sh
This pull request fixes #830 
The directory structure is of the form Go_programming
=> Added Go programming source codes

sorting/insertion_sort/insertion_sort.js
=> insertion sort in js -fix for #881

CONTRIBUTORS.md, is_prime/cs/isPrime.cs
=> Added IsPrime in C#

fibonacci/js/recursiveFibonacciNoMemo.js, multiples/multiples.js, palindrome/palindrome.java
=> Generate multiples in JavaScript 

web_server/web_server.rb
=> Adds Web Server in Ruby

hello_world/Hello-world.js
=> Added Hello World In JavaScript

linkedList_java/.classpath, linkedList_java/.gitignore, linkedList_java/.project, linkedList_java/README.md, linkedList_java/src/com/vaibhav/myImpl/SinglyLinkedList/ApplicationTest.java, linkedList_java/src/com/vaibhav/myImpl/SinglyLinkedList/LinkedList.java, linkedList_java/src/com/vaibhav/myImpl/SinglyLinkedList/List.java, linkedList_java/src/com/vaibhav/myImpl/SinglyLinkedList/Node.java, linkedList_java/src/com/vaibhav/myImpl/SinglyLinkedList/package-info.java
I have implemented Singly Linked list data structure in java.
=> LinkedList implementation in java

Endianness/determine_endianess.c
- [ x] This pull request fixes #862.
=> Fixed Issue #862: To determine endianness of machine

password_generator/js/index.html, password_generator/js/js.js
fixes #857 
-  [/] This pull request fixes #issue_reference (Create a issue if not already present.)
- [/] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [/] Don't duplicate stuff.
=> Add function to generate password with javascript

ftp_python/.gitignore, ftp_python/LICENSE, ftp_python/README.md, ftp_python/config.example.yml, ftp_python/myftp/config.py, ftp_python/myftp/myftp.py, ftp_python/setup.py, ftp_python/tests/test_ftp.py
Signed-off-by: Lays Rodrigues <laysrodriguessilva@gmail.com>
=> First commit

alpha_to_num/AlphaToInt.cpp
fixes #852 
-  Created a alpha_to_num folder
=> Add alpha to num c++

encryption_algorithms/js/aes.js
=> AES algorithm in JavaScript

tic_tac_toe/c#/TicTacToe.cs
=> add Tic-Tac-Toe in C# #874

modular_exponential/modular_exponential.cpp
=> Added Modular Exponential in C++

check_ean_13/python/ean13.py
=> Add checking EAN-13 for Python (#896)

balance_brackets/python/brackets.py
=> Create Balanced Brackets in Python

fibonacci/python/fibonacci-function.py
=> Create Fibonnaci in Python, using the non-recursive formula

hello_world/php/hello_world.php
You don't need a close tag in PHP files.
And there was a silly typo in "Hello, World" (you always need a comma there)
=> [BOYSCOUT] Fix typo in hello, world

wiki_crawler/Crawl.java, wiki_crawler/ProxyAuthenticator.java, wiki_crawler/StaticCrawl.java
=> added web wiki crawler in java

shortest_fastest_foobar/foobar.py
- This pull request solve the foobar task in python.
- It is a sub directory of programming/shortest_fastest_foobar/
=> Create foobar.py file

mathematical_operations/basic_arithmetic.py
- This pull request fixes the #issue of basic mathematical operation in Python
- The directory structure is of the form /programming/mathematical_operations/
=> Create basic_arithmetic.py file

games_dev/TicTacToe/TicTacToe.html, games_dev/TicTacToe/tictactoe.css, games_dev/TicTacToe/tictactoe.js
=> Add Tic Tac Toe game in JavaScript

alpha_to_num/alpha_to_num.cpp
=> An alternative implementation of alpha_to_num

sorting/merge_sort/mergesort.c, sorting/selection_sort/selectionsort.c
=> Merge Sort in C

NthFibonacci/NthFibonacci.clj
=> fixes #914, implementing nth_fibonacci in clojure

client_server/chat_python/client.py
=> Client-Server model chat implementation in python fixes#915

client_server/chat_python/server.py
=> Create server.py fixes #915

fibonacci/lua/fibonacci.lua
=> add fibonacci lua

web_server/web_server.c
Directory = programming/web_server/
=> web_server.c

shell_scripting/install_all_packages.sh
This script is useful for installing missing and all packages on Debian and Ubuntu systems.
=> installation.sh

tic_tac_toe/python/tictactoe.py
- This pull request fixes #952 
- The directory structure is of the form (tic_tac_toe/python)
The implementation uses Tkinter in python3.
=> Add TicTacToe in python

recursion/python/fibonacci.py
=> add py fibonacci fixes #957

hello_world/erlang/hello_world.erl
=> Creating "hello world" in Erlang

raspberry_pi/program_bcm.py
Make 2 LEDs connected to Raspberry PI to blink and back and forth
=> Raspberry PI 2 LEDs blinking

recursion/rust/tower_of_hanoi.rs
=> Implement recursive tower of hanoi in rust

recursion/js/flattenArray.js
=> Flatten array

modular_exponential/modular_exponential.java
=> Added Modular Exponential in Java

modular_exponential/modular_exponential.cs
=> Added Modular Exponential in C#

modular_exponential/modular_exponential.py
=> Added Modular Exponential in Python

CONTRIBUTORS.md, hello_world/Hello-Hacktoberfest.js, hello_world/Hello-world.js
=> Hello_Hacktoberfest_Codealtgeek

numbers/is_adam_number/js/adam.js
=> Adam Number

linked_list/java/Print n’th node from the end of a Linked List.java
=> Create Print n’th node from the end of a Linked List.java

loop/java/DifferentLoops.java
Added different way to loop in Java
=> Added loops for Java

CONTRIBUTORS.md, hello_world/ruby/hello_world_rb2.rb
=> Ruby: missing 'puts' for hello world

sorting/insertion_sort/insertion_sort.cpp
=> Insertion Sort in CPP

tic_tac_toe/javascript/react/tic-tac-toe.js
=> Create tic-tac-toe.js in React - issue #991

searching/linear_search/swift/linear_search.swift
=> fixes #994

sorting/bubble_sort/bubble_sort.cs
- [X ] This pull request fixes #999
=> Added Bubble Sort in C#

crash_your_pc/boom.py
This pull request fixes #1003 
Directory: crash_your_pc
=> added boom.py

games_dev/Snake_Game/snake.py
The classic snake game built in python via pygame
=> Add Snake game in Python

CONTRIBUTORS.md, halloween/isHalloween.js
Added a new 'halloween' directory and created a js file to check if the
current day is Halloween
=> Michael Hurley contribution

dynamic_css/README.md
=> fixes #1010

node_js/node.js, web_server/node.js/node.js
=> add nodejs

hello_world/python/hello_world_thammk.py, io_operations/text_writer.py
- [#1117] This pull request fixes #1117  (Create a issue if not already present.)
- [ IO_operations] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
=> Added a Text Writer in Python

primes_python/primes.py
=> Fixes Issue #1113

queues/Queues - Extended.cpp, searching/binary_search/php/binary_seach.php, searching/linear_search/php/linear_seach.php
=> Kavinda1995 php binary search

sorting/insertion_sort/insertion_sort.py
=> Change insertion sort in python

queues/Queues - Extended.cpp, searching/linear_search/php/linear_seach.php
=> Kavinda1995 php linear search

queues/Queues - Extended.cpp
=> added cpp queues

halloween/isHalloween.py, halloween/isHalloween.swift
- [✔ ] This pull request fixes #1060 (Create a issue if not already present.)
- [ ✔] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [✔ ] Don't duplicate stuff.
=> Add isHalloween.py and fix isHalloween.swift

ProLog/Max.pl, ProLog/Max.pl~
Pull Request modifications include ProLog script (only to insure diversity among your programmes)
=> ProLog addition

kotlin_examples/NullSafety.kt, multiplication_without_multiply_operator/multiplication.c++, multiplication_without_multiply_operator/multiplication.java
=> Kotlin examples

hindi_java/HindiToHex.java
=> Hindi to hex

hello_world/ruby/hello.rb
- [x ] This pull request fixes #issue_reference (Issue # 1069.)
- [x ] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [x ] Don't duplicate stuff.
=> hello_world_script_in_Ruby

sorting/radix_sort/radix_sort.cpp
=> radix sort in c++

Vue/index.html
=> Ajtruex helloworl vue

atm/python/atm.py
=> Create simple ATM note simulator in Python

encryption_algorithms/c/caesar.c
=> Implement a Caesar Cipher program in C.

count_lattice_paths/Lattice Paths Counter.py
=> Added my program

InfixToPostfix/infix_to_postfix.cpp, infix_postfix/infix_to_postfix.cpp
=> Added a program to convert an infix expression to postfix expression in c++

gcd/php/gcd.php
=> Added GCD for PHP

make_timer/make_timer.py
- This pull request fixes the issue of creating a timer in Python
- The directory structure is of the form /programming/make_timer/
=> Create make_timer.py file

greater number/greater.py
Checks two numbers and prints the greater one. Added via upload.
- [- ] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
=> Greater number

mathematical_operations/cpp/Mod_operations.cpp
=> Add modular operations in cpp (Fixes #1074)

mathematical_operations/js/math_operations.js, package.json
=> Created mathematical operations program in JavaScript (fixes issue #1072)

date_programs/tomorrow_date.py
- This pull request fixes the issue of getting tomorrow's date using Python.
- The directory structure is of the form /programming/date_programs/
=> Create tomorrow_date.py file

gcd/go/gcd.go
=> adding go code for calculating gcd

finding_vars/finder.cpp
=> Added folder finding_vars

BC_Ferry_Web_Scraper
A CLI Web Scraper that scrapes BC Ferries to find out the departure and arrival times of ferries.
=> Added BC_Ferry_Web Scraper

gcd/ruby/gcd.rb
=> Adding custom input from command line

numbers/reverse_a_number/java/chandan
an easy program to reverse the number
=> reverse number program

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, README.md
=> fixed typo that was annoying me 

age_counter/cpp/count_the_age_person.cpp
added clrscr()- to clear the previous output & made the output lines match each other's indentation.
- [✔ ] This pull request fixes #issue_1032 - #1032
- [✔ ] The directory structure is of the form (age_counter/cpp) 
- [✔ ] Don't duplicate stuff.
=> made the output structure more satisfying

factorial/C/factorial.c
added clrscr()- to clear the previous output & made the output lines match each other's indentation.
- [✔ ] This pull request fixes #issue_1032 - #1035
- [✔ ] The directory structure is of the form (factorial/c) 
- [✔ ] Don't duplicate stuff.
=> Made the o/p of the program more readable & styled

fibonacci/c/fibonacci.c
added comments in the code to make it easy to understand & clrscr() function to erase the previous output.
- [ ✔ ] This pull request fixes #issue_1037 - #1037
- [ ✔ ] The directory structure is of the form (fibonacci/c) 
- [ ✔ ] Don't duplicate stuff.
=> Made the code user friendly

searching/linear_search/c/linear_search.c
removed the extra , unnecessary lines & implemented the core logic .
- [ ✔ ] This pull request fixes #issue_1039 - #1039 
- [ ✔ ] The directory structure is of the form (searching/linear_search/c) 
- [  ✔] Don't duplicate stuff.
=> Made the code short and easy to understand

sieve_of_eratosthenes/sieve.py
Seive of eratosthenes in Python 2 .
=> Added seive of eratosthenes in Python2

gameOFlifeJava/Game.java, gameOFlifeJava/read
=> Microprogrammer c game o flife in java

hello_world/hack/hello_world.hh
=> Add hello world for hack language

string_manipulations/repeatify/repeatify.js
closes #1127 
@t2013anurag 
* Create a repeatify folder under string_manipulations
* Create a JS function to repeat a string called repeatify.js
- [x ] This pull request fixes #issue_reference (Create an issue if not already present.)
- [x ] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [ x] Don't duplicate stuff.
=> fixes #1127

c_programming/calculator.c
=> added calculator.c

conversions/length/convertYardsToMeters.js
=> Add convertYardsToMeters in javascript

factorial/factorial_using_dp/fact_dp.js
=> Factorial using Dynamic Programming in JavaScript

numbers/palindrome/palindrome.js
=> added palindrome.js

numbers/left_variadic_multiplication_function/product.js
- [x ] This pull request fixes #1142 
- [x ] The directory structure is of the form (numbers\left_variadic_multiplication_function) 
- [x ] Don't duplicate stuff.
=> added left variadic product function

encryption_algorithms/python/Hill_Cipher_Encryption_Decryption.py, index.html
=> Hacktober Fest:: Issue #1147 Updated Code in Python

ReverseWordJS/ReverseWord.js
=> Added ReverseWord Program in JS

client_server/java/Client.java, client_server/java/Server.java
#1181 Pull Request checklist - #1181 
- This pull request fixes #1181 
- The directory structure is of the form. (client_server/java)
- Don't duplicate stuff.
=> #1181 Issue - creating Socket communication with Java

TempFileCleanup.py
Create a GUI that will remove temp files and clean disk.
=> Temp file deletion in python with Tkinter

hello_world/c/helloworld.c
=> updated hello_world.c

beginner_programming/age_counter/Csharp/Program.cs
=> Add ageCounter program in c#

machine_learning/Pandas_Dataframe/Create_DataFrame.py
=> Added Create Dataframe with Pandas in Machine Learning

svimanet_python/urbanDictionary.py
=> added a python program for urban dictionary

searching/binary_search/rust/binary_search.rs, searching/binary_search/rust/binary_search_tree.rs, searching/linear_search/rust/linear_search.rs
-  This pull request fixes #1162
=> Searching in Rust Language

binary_search/c/binary_search.c
=> Added binary search in C

halloween/isHalloween.rb
=> Added isHalloween.rb

index.html
Some changes
- Redesigned site to modern look 
- Changed background colour to 'Midnight Blue'
- Used 'Lobster' font for title
- Attractive button
You can see changes here
https://rawgit.com/akshay196/programming/gh-pages/index.html
=> Change design of site

raspberry_pi/remote_control.py
This program helps to control linux systems via telegram chat bot.
This script should run on boot at the target system having internet connection.
=> remote control linux

egg_dropping_puzzle/egg_dropping_puzzle.cpp
- [ :+1:   ] This pull request fixes #issue_reference (Create an issue if not already present.)
- [  :+1:  ] The directory structure is of the form (directory_name) (If directory doesn't exist, create a new.)
- [  :+1:  ] Don't duplicate stuff.
=> Added Egg Dropping Puzzle

CONTRIBUTORS.md, client_server/go/ReadMe.md, client_server/go/app.go
=> HTTP Server in Go

sorting/selection_sort/selection_sort/racket.rkt
=> racket selection sort

crash_your_pc/SORRY.bat
Create a virus not only to shut down your computer but rid it of it's OS and say Sorry. Not!
=> Create Sorry! Virus

sorting/sleep_sort/sleep_sort.c
=> Added Sleep Sort

palindrome/ruby/palindrome.rb
=> Fixes #1807

date_programs/ruby/todays_date.rb
=> Fixes #1803

hello_world/assembly/i_386/hello.asm
=> Added hello with username in assembly i_368 for issue #800 (#988)

hello_world/BASIC/hello_world.bas
=> Hello, World in BASIC

egg_dropping_puzzle/egg_dropping_puzzle.php
=> Add egg dropping puzzle

basic-blockchain/README.md, basic-blockchain/python/Blockchain.py
A very simple blockchain in python with simple mining to create and verify each blocks in blockchain
=> Basic blockchain with simple mining similar to as bitcoin

fibonacci/c/fibUsingArray.c, sorting/SortingTimeComplx.cpp
Pull Request checklist complete. Adds an optimized program to #2020
=> Added optimized Fibonacci program in C using array #2020

hello_world/hello_world.c
=> Hello world program in c
